name: Build (Angular + Server)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install root dependencies
        run: npm install

      - name: Install server dependencies
        run: npm install --prefix server

      - name: Install client dependencies
        run: npm install --prefix client

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular client
        run: npm run build --prefix client
