name: CI (No Build)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install root dependencies
        run: npm install

      - name: Install server dependencies
        run: npm install --prefix server

      - name: Install client dependencies
        run: npm install --prefix client
